import type { ErroComum } from '@/lib/formation/schema'

// Catálogo de erros comuns da formação. Cada erro tem um id estável, usado
// por opções de cartões e por exercícios para diagnosticar o que o aluno
// pensou. Um erro aparece aqui uma vez só, mesmo que volte em várias aulas.

export const ERROS: ErroComum[] = [
  {
    id: 'valor-de-face',
    nome: 'lê o algarismo, não o valor da casa',
    causa: 'Trata cada algarismo como o próprio número, sem considerar a posição.',
    exemplo: 'Em 4.072, diz que o 7 vale 7.',
    desmonte: 'Acender a casa das dezenas e mostrar as 7 barras de 10 embaixo dela: 7 dezenas são 70.',
  },
  {
    id: 'casa-errada',
    nome: 'erra a casa por uma posição',
    causa: 'Conta as casas a partir do lado errado, ou pula uma.',
    exemplo: 'Em 4.072, diz que o 7 vale 700.',
    desmonte: 'Rotular as casas da direita para a esquerda (U, D, C, M) e contar junto com o aluno.',
  },
  {
    id: 'concatena-casas',
    nome: 'escreve as casas coladas',
    causa: 'Escreve o número como se fala, juntando os pedaços: "seiscentos" (600) e "nove" (9).',
    exemplo: '"Seiscentos e nove" vira 6009.',
    desmonte: 'Montar no quadro posicional: 6 centenas, 0 dezenas, 9 unidades. O número tem três casas, não quatro.',
  },
  {
    id: 'esquece-zero',
    nome: 'esquece o zero que guarda o lugar',
    causa: 'Acha que o zero "não vale nada" e pode sumir.',
    exemplo: '"Seiscentos e nove" vira 69.',
    desmonte: 'Tirar o zero do quadro: o 6 escorrega para as dezenas e as 6 placas viram 6 barras. Sobram 69, um número bem menor.',
  },
  {
    id: 'estudo-so-observar',
    nome: 'confunde reconhecer uma resposta com conseguir resolver',
    causa: 'A familiaridade ao reler ou assistir é tratada como evidência de que consegue produzir os passos sozinho.',
    exemplo: 'Lê uma resolução, ela parece conhecida e segue sem fazer uma tentativa própria.',
    desmonte: 'Cobrir a resolução e abrir uma questão nova da mesma ideia; comparar uma folha apenas relida com uma folha que contém passos produzidos pelo aluno.',
  },
  {
    id: 'estudo-sem-papel',
    nome: 'trata o papel como condição para começar',
    causa: 'Confunde a recomendação de caderno quadriculado com uma exigência que impede estudar quando não tem papel.',
    exemplo: 'Adia uma tentativa mesmo tendo uma forma de escrever no rascunho da tela.',
    desmonte: 'Mostrar a mesma tentativa registrada no papel e no rascunho da tela: ambos permitem guardar os passos e comparar depois.',
  },
  {
    id: 'estudo-dica-resposta',
    nome: 'usa resolução como substituta da tentativa',
    causa: 'Abre ou copia a resposta antes de tentar e conta a cópia como se tivesse resolvido sem apoio.',
    exemplo: 'Copia a solução completa ao travar e considera esse registro um acerto independente.',
    desmonte: 'Separar visualmente tentativa própria, tentativa com pista e cópia da resolução; depois fechar o apoio e pedir uma questão nova da mesma ideia.',
  },
  {
    id: 'estudo-voz-obrigatoria',
    nome: 'supõe que ouvir a Vega é obrigatório',
    causa: 'Confunde uma opção de acesso por áudio com um requisito para participar da aula.',
    exemplo: 'Quer estudar em silêncio, mas acha que precisa ligar a voz para continuar.',
    desmonte: 'Manter texto, visuais e tarefas visíveis com a voz desligada; ligar e desligar o áudio sem mudar a tarefa ou abrir a resolução.',
  },
  {
    id: 'estudo-sem-revisao',
    nome: 'trata conclusão da aula como lembrança permanente',
    causa: 'Acha que uma ideia vista ou corrigida não precisa voltar em tentativas futuras.',
    exemplo: 'Pula toda questão antiga porque já terminou aquela aula uma vez.',
    desmonte: 'Trazer uma questão antiga com a resposta coberta, registrar a tentativa e só então conferir; a evidência vem do que consegue recuperar agora.',
  },
  {
    id: 'estudo-pula-sem-tentar',
    nome: 'confunde o atalho Já sei isso com prova de domínio',
    causa: 'Trata a autodeclaração de conhecimento como suficiente para marcar domínio, sem verificar numa tentativa.',
    exemplo: 'Escolhe Já sei isso e considera a habilidade dominada sem resolver uma questão.',
    desmonte: 'Desenhar o atalho indo à Sua vez, sem selo de domínio, e uma seta de retorno à explicação após a tentativa.',
  },
  {
    id: 'diagnostico-resposta-ajudada',
    nome: 'usa resposta após ajuda como evidência do ponto de partida',
    causa: 'Não distingue uma primeira tentativa sem ajuda de uma resposta produzida depois de ver dica ou resolução.',
    exemplo: 'No diagnóstico, copia a resolução e registra essa resposta no lugar da primeira tentativa.',
    desmonte: 'Preservar duas folhas separadas, primeira resposta e tentativa com apoio; a resposta posterior não sobrescreve o registro inicial.',
  },
  {
    id: 'diagnostico-generaliza-dominio',
    nome: 'generaliza uma amostra para toda a formação',
    causa: 'Supõe que acertar alguns itens da U1 comprova domínio de assuntos que não foram avaliados.',
    exemplo: 'Acerta cinco perguntas de numeração e conclui que já domina frações, operações e álgebra.',
    desmonte: 'Delimitar as cinco perguntas dentro da U1 e deixar operações, frações e álgebra sem avaliação; recomendar confirmar a U1 na prática, sem selo global de domínio.',
  },
  {
    id: 'conta-grupos-como-unidades',
    nome: 'conta grupos como unidades soltas',
    causa: 'Conta cada barra, placa ou caixa como uma unidade, esquecendo quantas unidades o grupo contém.',
    exemplo: 'Duas barras de dez e sete cubos são registrados como 9 unidades, em vez de 27.',
    desmonte: 'Abrir as duas barras em dez cubos cada, mantendo os sete cubos soltos. Contrastar nove objetos desenhados com 27 unidades; a embalagem muda, a quantidade não.',
  },
  {
    id: 'troca-incompleta',
    nome: 'faz uma troca que não conserva a quantidade',
    causa: 'Não confere os dez grupos exatos necessários à troca, ou deixa algum grupo desaparecer ao reorganizar as peças.',
    exemplo: 'Troca 9 unidades por 1 dezena; ou, ao reorganizar 13 dezenas em 1 centena, deixa só 2 dezenas fora da placa.',
    desmonte: 'Usar molduras de dez encaixes e acompanhar cada peça antes e depois. Em 9 unidades, um encaixe fica vazio; em 13 dezenas, dez entram na placa e três permanecem fora.',
  },
  {
    id: 'sobra-na-casa-errada',
    nome: 'põe a sobra numa ordem diferente',
    causa: 'Confunde a quantidade de grupos completos com a quantidade de unidades restantes, ou muda o valor das peças que sobraram.',
    exemplo: 'Duas dezenas e sete unidades viram 72; ou três barras e sete cubos são registrados como sete dezenas e três unidades.',
    desmonte: 'Conservar o tipo de cada peça e rotular D nas barras e U nos cubos. Alinhar os algarismos com esses conjuntos: duas barras de dez e sete cubos ocupam D=2 e U=7.',
  },
  {
    id: 'descarta-sobra',
    nome: 'descarta as unidades que sobram',
    causa: 'Considera apenas os grupos completos e trata as peças restantes como se não fizessem parte da quantidade.',
    exemplo: 'Duas dezenas e sete unidades são registradas como 20, ignorando as sete peças soltas.',
    desmonte: 'Manter as sobras no palco e contorná-las; abrir os grupos e juntar todas as unidades para conferir que as peças soltas também entram no total.',
  },
  {
    id: 'classe-errada',
    nome: 'confunde milhares, milhões e bilhões',
    causa: 'Lê ou escreve um grupo de algarismos com o nome de outra classe, conta os trios pelo lado errado ou ignora uma classe vazia.',
    exemplo: 'Chama 1.000.000.000 de um milhão; ou põe o 3 de três milhões na classe dos milhares.',
    desmonte: 'Alinhar as unidades à direita e marcar trios: unidades, milhares, milhões, bilhões. Comparar um milhão e um bilhão no mesmo quadro; o 1 ocupa classes diferentes.',
  },
  {
    id: 'separador-decimal',
    nome: 'confunde o separador de milhar com o decimal',
    causa: 'Interpreta a pontuação usando outra convenção de idioma, sem conferir o formato indicado na fonte.',
    exemplo: 'Num arquivo explicitamente em inglês, lê 12,500 como doze vírgula quinhentos, em vez de doze mil e quinhentos.',
    desmonte: 'Ligar a etiqueta de idioma ao separador entre 12 e 500: português 12.500 e inglês 12,500 mostram a mesma quantidade. Alertar que, no padrão brasileiro, a vírgula é decimal; não supor um formato quando o idioma é desconhecido.',
  },
  {
    id: 'compara-pela-ultima-casa',
    nome: 'compara só o último algarismo',
    causa: 'Decide qual natural é maior pelas unidades e ignora as casas de maior valor.',
    exemplo: 'Diz que 479 é maior que 482 porque 9 é maior que 2.',
    desmonte: 'Alinhar as casas: as centenas empatam e as dezenas já decidem, 8 é maior que 7. Na reta, 482 fica à direita de 479.',
  },
  {
    id: 'ignora-quantidade-casas',
    nome: 'ignora a quantidade de algarismos dos naturais',
    causa: 'Compara algarismos isolados de naturais com quantidades diferentes de casas, sem considerar seu valor posicional.',
    exemplo: 'Escolhe 89 em vez de 104, apesar de 104 já ter uma centena inteira.',
    desmonte: 'Colocar 100 como referência: 89 fica antes e 104 depois. Alinhar as casas e mostrar que 104 tem uma centena, ausente em 89. Contar só algarismos, sem zeros à esquerda.',
  },
  {
    id: 'inverte-reta',
    nome: 'lê a reta no sentido contrário',
    causa: 'Associa o lado esquerdo ao maior valor ou organiza uma ordem crescente da direita para a esquerda.',
    exemplo: 'Na reta orientada para a direita, escolhe 7 como maior que 12.',
    desmonte: 'Percorrer os inteiros de 7 até 12 na reta; a contagem cresce para a direita. Ler a ordem crescente da esquerda para a direita.',
  },
  {
    id: 'intervalos-desiguais',
    nome: 'muda o valor de intervalos iguais',
    causa: 'Atribui avanços numéricos diferentes a distâncias iguais em uma mesma escala de reta.',
    exemplo: 'Em uma reta de dez em dez, rotula três marcas igualmente espaçadas como 0, 10 e 50.',
    desmonte: 'Usar o trecho de 0 a 10 como gabarito de comprimento; o intervalo seguinte termina em 20. Para chegar a 50 são necessários cinco intervalos desse tamanho.',
  },
  {
    id: 'arredonda-sempre-para-cima',
    nome: 'sempre sobe ao arredondar',
    causa: 'Trata arredondar como avançar para o próximo múltiplo, mesmo quando a marca menor está mais próxima.',
    exemplo: 'Arredonda 243 à dezena como 250.',
    desmonte: 'Marcar 240, 243, 245 e 250 numa mesma escala: 243 fica antes do meio e o trecho até 240 é mais curto. Contrastar com 247, que fica depois do meio.',
  },
  {
    id: 'olha-casa-errada',
    nome: 'usa outra casa para decidir o arredondamento',
    causa: 'Olha sempre a unidade ou o primeiro algarismo, sem relacionar a casa decisiva à precisão pedida.',
    exemplo: 'Arredonda 2.460 à centena como 2.400 porque a unidade é zero.',
    desmonte: 'Marcar 2.400 e 2.500 e o meio 2.450: 2.460 está depois do meio. Realçar a dezena 6, primeira casa à direita da centena; unidade para dezena, dezena para centena, centena para milhar.',
  },
  {
    id: 'empate-para-baixo',
    nome: 'escolhe o menor no empate',
    causa: 'Aplica outra convenção ou sempre corta as casas, em vez de escolher o maior no empate declarado pela formação.',
    exemplo: 'Arredonda 995 à dezena como 990.',
    desmonte: 'Mostrar 995 no meio exato entre 990 e 1.000 e dois trechos de mesmo comprimento. Relembrar a convenção: escolher o maior no empate; o destino pode abrir uma nova casa.',
  },
  {
    id: 'estimativa-exata',
    nome: 'confunde aproximação com igualdade',
    causa: 'Usa = entre o valor original e um arredondamento diferente ou acredita que o arredondamento altera a quantidade real.',
    exemplo: 'Escreve 243 = 200 ao arredondar à centena e diz que a viagem ficou menor.',
    desmonte: 'Conservar o ponto exato 243 e um marcador aproximado em 200 em posições diferentes. Escrever 243 ≈ 200; mostrar dois rótulos 200 no mesmo ponto para justificar 200 = 200.',
  },
  {
    id: 'aproximacao-garante-limite',
    nome: 'toma um valor aproximado como garantia de limite',
    causa: 'Compara o número arredondado com um teto ou quantidade disponível e ignora que o valor exato pode ser maior.',
    exemplo: 'Com 104 convites e 100 envelopes, diz que há um envelope por convite porque 104 arredonda para 100.',
    desmonte: 'Marcar os valores exatos na reta: 104 fica à direita de 100. A aproximação ajuda a avaliar o tamanho, mas a garantia exige comparar as quantidades exatas.',
  },
]

export function getErro(id: string): ErroComum | undefined {
  return ERROS.find((e) => e.id === id)
}
